# The purpose of this project is to demonstrate the ability to collect, work with, and clean a data set. 
# The goal is to prepare tidy data that can be used for later analysis.
# The script extracts and cleans data generated by a group of 30 volunteers within an age bracket of 19-48 years.
# Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) 
# wearing a smartphone (Samsung Galaxy S II) on the waist.
# The full description of the data set is available at:
# http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

library(plyr)

f01.read.merge.datasets = function() {
    message("* f01.read.merge.datasets *")
    # Read data
    message("Extracting X_train.txt")
    tr.x <- read.table("getdata-projectfiles-UCI HAR Dataset/UCI HAR Dataset/train/X_train.txt")
    message("Extracting y_train.txt")
    tr.y <- read.table("getdata-projectfiles-UCI HAR Dataset/UCI HAR Dataset/train/y_train.txt")
    message("Extracting subject_train.txt")
    tr.subject <- read.table("getdata-projectfiles-UCI HAR Dataset/UCI HAR Dataset/train/subject_train.txt")
    message("Extracting X_test.txt")
    te.x <- read.table("getdata-projectfiles-UCI HAR Dataset/UCI HAR Dataset/test/X_test.txt")
    message("Extracting y_test.txt")
    te.y <- read.table("getdata-projectfiles-UCI HAR Dataset/UCI HAR Dataset/test/y_test.txt")
    message("Extracting subject_test.txt")
    te.subject <- read.table("getdata-projectfiles-UCI HAR Dataset/UCI HAR Dataset/test/subject_test.txt")
    message("Merge data")
    m.x <- rbind(tr.x, te.x)
    m.y <- rbind(tr.y, te.y)
    m.subject <- rbind(tr.subject, te.subject)
    message("merge train and test datasets and return")
    list(x=m.x, y=m.y, subject=m.subject)
}

f02.get.mean.std.data = function(px) {
    # From the full dataset extract only the measurements on the mean
    # and standard deviation for each measurement.

    # Read the feature txt file
    message("* f02.get.mean.std.data *")
	message("Extracting features.txt")
    features <- read.table("getdata-projectfiles-UCI HAR Dataset/UCI HAR Dataset/features.txt")
    message("Get the mean and std columns")
    mean.col <- sapply(features[,2], function(x) grepl("mean()", x, fixed=T))
    std.col <- sapply(features[,2], function(x) grepl("std()", x, fixed=T))
    message("Extract only the mean and std columns from the data")
    epx <- px[, (mean.col | std.col)]
    message("Populate the column names")
    colnames(epx) <- features[(mean.col | std.col), 2]
    message("Remove unwanted characters from column names")
    names(epx) <- gsub("\\(|\\)", "", names(epx))
    names(epx) <- tolower(names(epx))
    epx
}

f03.replace.activities = function(py) {
    message("* f03.replace.activities *")
    message("Use descriptive activity names to name the activities in the dataset")
    colnames(py) <- "activity"
    py$activity[py$activity == 1] = "WALKING"
    py$activity[py$activity == 2] = "WALKING_UPSTAIRS"
    py$activity[py$activity == 3] = "WALKING_DOWNSTAIRS"
    py$activity[py$activity == 4] = "SITTING"
    py$activity[py$activity == 5] = "STANDING"
    py$activity[py$activity == 6] = "LAYING"
    py
}

f04.combine.all.data <- function(px, py, psubjects) {
    message("* f04.combine.all.data *")
    message("Combine mean and std values (x), activities (y) and subjects into one data frame.")
    cbind(px, py, psubjects)
}

f05.calculate.average = function(pdf) {
    message("* f05.calculate.average *")
	message("Create a clean dataset with the average of each variable for each activity and each subject.")
    clean.data <- ddply(pdf, .(subject, activity), function(x) colMeans(x[,1:60]))
    clean.data
}

f06.uci.har.main = function() {
    # reads x, y and subjects data for the training and test datasets and merges them. Returns a list
    # of three dataframes: X, y, and subject
    lmd <- f01.read.merge.datasets()
    # Extract only the mean and standard deviation measurements from the dataset.
    lx <- f02.get.mean.std.data(lmd$x)
    # Name the activities
    ly <- f03.replace.activities(lmd$y)
    # Use descriptive column name for subjects
    colnames(lmd$subject) <- c("subject")
    # Combine all the data frames into one dataset
    all.x.y.sub <- f04.combine.all.data(lx, ly, lmd$subject)
    # Create a clean dataset with the average of each variable for each activity and each subject.
    lcd <- f05.calculate.average(all.x.y.sub)
    # Write the tidy dataset into a csv file
    write.table(lcd, "uci_har_clean_data.txt", row.names=FALSE)
}